### ISSUE TITLE
Impossible to export image in docx

### ISSUE THREAD

**Issue by manutheblacker** [gongph/html2docx#3]
Hello @gongph , I've used your plugin and it's pretty cool.
I'm facing an issue, i'm building a django app where the user will be able to export his current page into docx file , the issue now is that the css and the images isn't exported into the docx.
What do you suggest for this issue?

**Comment by Im-praveen** [comment]
You can use inline base64 image not any link, that works in my case.

CSS you need to attach as styleCss property in 
saveAsDocx({
			selector: '#my-selector',
			margins: {
				top: 720
			},
			styleCss: '<style>table{font-family: myfont;}</style>'
		});

**Comment by Im-praveen** [comment]
You can use inline base64 image in place image-link, that works in my case.

CSS you need to attach as styleCss property in
saveAsDocx({
selector: '#my-selector',
margins: {
top: 720
},
styleCss: '<style>table{font-family: myfont;}</style>'
});
